apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  {{- template "common.metadata" . }}
spec:
  #type: LoadBalancer
  ports:
    - port: 443
      protocol: TCP
      targetPort: 1337
  selector:
    app: {{ .Values.app.name }}
---