# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "kube-system"

app:
  name: "app-monitoring-webhook"
  environment: "test"
  owner : "Microsoft"
  image: "mcr.microsoft.com/applicationinsights/codeless-attach/mutating-webhook:test7_23_7"
  agents: "gearamaaks.azurecr.io/public/applicationinsights/codeless-attach/ai_agents:test7_23_7"
  caBundle: "baseBundle"
  iKey: "target ikey2"
  telemetryIkey: "320dcf98-173f-429b-ab39-df8b4951fb94"
  telemetryConnString: "InstrumentationKey=320dcf98-173f-429b-ab39-df8b4951fb94"
  
replicaCount: 1

nodeSelector: "{ \"beta.kubernetes.io/os\": linux }"
